@startuml

title 状態遷移図
skinparam shadowing false


state load as "ロード画面" 

state howTo as "HowTo画面"
    howTo : 次へボタン
    howTo : 前へボタン
    howTo : プレイボタン

state players as "プレイヤー数入力画面"
    players : プレイヤー数入力フォーム
    players : 次へボタン

state question as "質問入力画面"
    question : ジャンル選択
    question : 質問入力フォーム
    question : スタートボタン

state answer as "回答画面"
    answer : Yesボタン
    answer : Noボタン

state result as "結果発表画面"
    result : 新規プレイボタン
    result : 同じ人数でプレイボタン

[*] --> load : アプリ起動
load --> howTo : ロード完了
howTo --> howTo : 次へ or 前へボタンタップ
howTo --> players : プレイボタンタップ
players --> question : フォーム入力後、次へボタンタップ
question --> answer : 各フォーム入力後、スタートボタンタップ
answer --> answer : Yes or Noボタンタップ（全員回答完了まで）
answer --> result : 全員回答完了
result --> players : 　新規プレイボタンタップ
result --> question : 同じ人数でプレイボタンタップ

@enduml
