# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'PartytionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SSBouncyButton', '~> 1.0'
  pod "GMStepper"

  # Pods for PartytionApp

  target 'PartytionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PartytionAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
