# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PartytionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "GMStepper"

  # Pods for PartytionApp

  target 'PartytionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PartytionAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
